### Successful login
POST https://lab2appdaniel.azurewebsites.net/login
Content-Type: application/json

{"username":"admin","password":"secret"}

### Failed login
POST https://lab2appdaniel.azurewebsites.net/login
Content-Type: application/json

{"username":"evil","password":"guess"}
